import React, { useState } from 'react';

interface MigrationStep {
  id: number;
  migrationFile: string;
  badge: string;
  title: string;
  goal: string;
  terminalCommand: string;
  modelsCode: string;
  sqlSnippet: string;
  schemaTables: {
    name: string;
    description: string;
    columns: { name: string; type: string; isPk?: boolean; isFk?: boolean; nullable?: boolean }[];
  }[];
  architectureInsight: string;
}

const MIGRATION_STEPS: MigrationStep[] = [
  {
    id: 1,
    migrationFile: '0001_initial.py',
    badge: 'Paso 1: Catálogo Base',
    title: 'Creación de Categoría y Producto',
    goal: 'Establecer las entidades maestras de nuestro inventario con una relación 1 a Muchos (1 Categoría tiene N Productos).',
    terminalCommand: `(venv) C:\\proyectos\\django\\ventas> python manage.py makemigrations ventas
Migrations for 'ventas':
  ventas/migrations/0001_initial.py
    - Create model Categoria
    - Create model Producto

(venv) C:\\proyectos\\django\\ventas> python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, ventas
Running migrations:
  Applying ventas.0001_initial... OK`,
    modelsCode: `# ventas/models.py (Fase 1)
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=150, db_index=True)
    codigo_barra = models.CharField(max_length=30, unique=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.PROTECT,
        related_name='productos'
    )

    def __str__(self):
        return f"{self.nombre} (\${self.precio})"`,
    sqlSnippet: `CREATE TABLE "ventas_categoria" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nombre" varchar(50) NOT NULL UNIQUE,
    "descripcion" text NOT NULL
);

CREATE TABLE "ventas_producto" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nombre" varchar(150) NOT NULL,
    "codigo_barra" varchar(30) NOT NULL UNIQUE,
    "precio" numeric(10, 2) NOT NULL,
    "stock" integer NOT NULL CHECK ("stock" >= 0),
    "categoria_id" bigint NOT NULL REFERENCES "ventas_categoria" ("id")
);`,
    schemaTables: [
      {
        name: 'ventas_categoria',
        description: 'Tabla maestra de familias de productos',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'nombre', type: 'VARCHAR(50) UNIQUE' },
          { name: 'descripcion', type: 'TEXT' },
        ],
      },
      {
        name: 'ventas_producto',
        description: 'Catálogo de artículos vendibles',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'nombre', type: 'VARCHAR(150)' },
          { name: 'codigo_barra', type: 'VARCHAR(30) UNIQUE' },
          { name: 'precio', type: 'NUMERIC(10, 2)' },
          { name: 'stock', type: 'INTEGER (>=0)' },
          { name: 'categoria_id', type: 'BIGINT', isFk: true },
        ],
      },
    ],
    architectureInsight: 'Usamos on_delete=models.PROTECT en la relación con Categoria para evitar que un administrador borre una categoría si todavía existen productos asignados a ella, protegiendo la integridad referencial.',
  },
  {
    id: 2,
    migrationFile: '0002_boleta_detalleboleta.py',
    badge: 'Paso 2: Transacciones de Venta',
    title: 'Cabecera y Detalle de Boleta (Master-Detail)',
    goal: 'Añadir la capacidad de emitir ventas con múltiples ítems. La boleta agrupa la transacción y el detalle almacena cada línea vendida.',
    terminalCommand: `(venv) C:\\proyectos\\django\\ventas> python manage.py makemigrations ventas
Migrations for 'ventas':
  ventas/migrations/0002_boleta_detalleboleta.py
    - Create model Boleta
    - Create model DetalleBoleta

(venv) C:\\proyectos\\django\\ventas> python manage.py migrate
Applying ventas.0002_boleta_detalleboleta... OK`,
    modelsCode: `# ventas/models.py (Fase 2 - Agregamos Boleta y DetalleBoleta)
from django.utils import timezone

class Boleta(models.Model):
    folio = models.CharField(max_length=20, unique=True, db_index=True)
    fecha = models.DateField(default=timezone.now)
    hora = models.TimeField(default=timezone.now)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    def __str__(self):
        return f"Boleta #{self.folio} - \${self.total}"


class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(
        Boleta,
        on_delete=models.CASCADE,
        related_name='detalles'
    )
    producto = models.ForeignKey(
        Producto,
        on_delete=models.PROTECT,
        related_name='ventas_detalle'
    )
    # REGLA DE ORO: Guardar copia exacta del precio al momento de la venta
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.PositiveIntegerField(default=1)
    total_linea = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.cantidad}x {self.producto.nombre} (\${self.total_linea})"` ,
    sqlSnippet: `CREATE TABLE "ventas_boleta" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "folio" varchar(20) NOT NULL UNIQUE,
    "fecha" date NOT NULL,
    "hora" time NOT NULL,
    "total" numeric(12, 2) NOT NULL
);

CREATE TABLE "ventas_detalleboleta" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "precio_unitario" numeric(10, 2) NOT NULL,
    "cantidad" integer NOT NULL CHECK ("cantidad" >= 0),
    "total_linea" numeric(10, 2) NOT NULL,
    "boleta_id" bigint NOT NULL REFERENCES "ventas_boleta" ("id") ON DELETE CASCADE,
    "producto_id" bigint NOT NULL REFERENCES "ventas_producto" ("id") ON DELETE RESTRICT
);`,
    schemaTables: [
      {
        name: 'ventas_boleta',
        description: 'Encabezado de la transacción comercial',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'folio', type: 'VARCHAR(20) UNIQUE' },
          { name: 'fecha', type: 'DATE' },
          { name: 'hora', type: 'TIME' },
          { name: 'total', type: 'NUMERIC(12, 2)' },
        ],
      },
      {
        name: 'ventas_detalleboleta',
        description: 'Líneas individuales de productos dentro de una boleta',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'boleta_id', type: 'BIGINT', isFk: true },
          { name: 'producto_id', type: 'BIGINT', isFk: true },
          { name: 'precio_unitario', type: 'NUMERIC(10, 2) (Instantánea)' },
          { name: 'cantidad', type: 'INTEGER' },
          { name: 'total_linea', type: 'NUMERIC(10, 2)' },
        ],
      },
    ],
    architectureInsight: '¿Por qué DetalleBoleta tiene su propio campo precio_unitario si Producto ya tiene precio? Porque los precios de los productos cambian con la inflación. Si lees el precio en vivo desde Producto, ¡las boletas de hace 6 meses cambiarían de total mágicamente! En facturación siempre se guarda una instantánea histórica (snapshot) del precio en el detalle.',
  },
  {
    id: 3,
    migrationFile: '0003_cliente_boleta_cliente.py',
    badge: 'Paso 3: Cliente Opcional',
    title: 'Añadir Cliente y Migrar Tablas con Datos Previos',
    goal: 'Permitir asociar un Cliente a la Boleta. Muchas ventas son a "Público General" (cliente anónimo), por lo que la relación DEBE ser opcional (null=True, blank=True).',
    terminalCommand: `(venv) C:\\proyectos\\django\\ventas> python manage.py makemigrations ventas
Migrations for 'ventas':
  ventas/migrations/0003_cliente_boleta_cliente.py
    - Create model Cliente
    - Add field cliente to boleta

(venv) C:\\proyectos\\django\\ventas> python manage.py migrate
Applying ventas.0003_cliente_boleta_cliente... OK`,
    modelsCode: `# ventas/models.py (Fase 3 - Agregamos Cliente y vinculamos a Boleta)
class Cliente(models.Model):
    rut_o_dni = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=120)
    email = models.EmailField(blank=True)
    telefono = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f"{self.nombre} ({self.rut_o_dni})"


# En Boleta agregamos la relación como NULLABLE:
class Boleta(models.Model):
    folio = models.CharField(max_length=20, unique=True, db_index=True)
    fecha = models.DateField(default=timezone.now)
    hora = models.TimeField(default=timezone.now)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    
    # NUEVO CAMPO: Opcional (admite ventas anónimas o sin registro)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,  # Si se borra el cliente, la boleta histórica NO se borra
        null=True,                  # Permite NULL en la BD (ventas anónimas)
        blank=True,                 # Permite dejar vacío en formularios
        related_name='boletas'
    )`,
    sqlSnippet: `CREATE TABLE "ventas_cliente" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "rut_o_dni" varchar(20) NOT NULL UNIQUE,
    "nombre" varchar(120) NOT NULL,
    "email" varchar(254) NOT NULL,
    "telefono" varchar(20) NOT NULL
);

-- Alteración segura de la tabla existente:
ALTER TABLE "ventas_boleta" 
ADD COLUMN "cliente_id" bigint NULL 
CONSTRAINT "ventas_boleta_cliente_id_fk" 
REFERENCES "ventas_cliente"("id") ON DELETE SET NULL;`,
    schemaTables: [
      {
        name: 'ventas_cliente (NUEVA)',
        description: 'Datos de contacto para clientes registrados',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'rut_o_dni', type: 'VARCHAR(20) UNIQUE' },
          { name: 'nombre', type: 'VARCHAR(120)' },
          { name: 'email', type: 'VARCHAR(254)' },
          { name: 'telefono', type: 'VARCHAR(20)' },
        ],
      },
      {
        name: 'ventas_boleta (ALTERADA)',
        description: 'Boleta ahora soporta tanto clientes registrados como anónimos',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'folio', type: 'VARCHAR(20) UNIQUE' },
          { name: 'fecha', type: 'DATE' },
          { name: 'hora', type: 'TIME' },
          { name: 'total', type: 'NUMERIC(12, 2)' },
          { name: 'cliente_id', type: 'BIGINT NULL (Opcional)', isFk: true, nullable: true },
        ],
      },
    ],
    architectureInsight: '¡Clave de Migraciones! Si la tabla Boleta ya tiene 1.000 boletas guardadas en tu sistema real y agregas cliente = ForeignKey(Cliente) sin null=True, Django te detendrá porque no sabría qué cliente asignarle a esas 1.000 boletas ya emitidas. Al usar null=True y on_delete=models.SET_NULL, la migración se ejecuta limpiamente y las boletas previas quedan registradas como compras a Público General.',
  },
  {
    id: 4,
    migrationFile: '0004_constraints_reglas_negocio.py',
    badge: 'Paso 4: Reglas de Integridad',
    title: 'CheckConstraints y Cálculos Automatizados',
    goal: 'Blindar la base de datos para impedir cantidades en cero o negativas, y automatizar el cálculo del subtotal en el método save().',
    terminalCommand: `(venv) C:\\proyectos\\django\\ventas> python manage.py makemigrations ventas
Migrations for 'ventas':
  ventas/migrations/0004_constraints_reglas_negocio.py
    - Create constraint chk_cantidad_positiva on model detalleboleta
    - Create constraint chk_precio_unitario_positivo on model detalleboleta

(venv) C:\\proyectos\\django\\ventas> python manage.py migrate
Applying ventas.0004_constraints_reglas_negocio... OK`,
    modelsCode: `# ventas/models.py (Fase 4 - Constraints y save() inteligente)
from django.core.validators import MinValueValidator

class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT, related_name='ventas_detalle')
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.PositiveIntegerField(
        default=1,
        validators=[MinValueValidator(1)]  # Validación en Formularios
    )
    total_linea = models.DecimalField(max_digits=10, decimal_places=2, editable=False)

    class Meta:
        constraints = [
            # Restricción a nivel de BASE DE DATOS SQL (nadie puede saltársela)
            models.CheckConstraint(
                check=models.Q(cantidad__gt=0),
                name='chk_cantidad_positiva'
            ),
            models.CheckConstraint(
                check=models.Q(precio_unitario__gte=0),
                name='chk_precio_unitario_positivo'
            ),
        ]

    def save(self, *args, **kwargs):
        # Si no se pasó precio, se toma automáticamente del producto actual
        if not self.precio_unitario:
            self.precio_unitario = self.producto.precio
        # Cálculo automático de la línea
        self.total_linea = self.precio_unitario * self.cantidad
        super().save(*args, **kwargs)`,
    sqlSnippet: `ALTER TABLE "ventas_detalleboleta" 
ADD CONSTRAINT "chk_cantidad_positiva" 
CHECK ("cantidad" > 0);

ALTER TABLE "ventas_detalleboleta" 
ADD CONSTRAINT "chk_precio_unitario_positivo" 
CHECK ("precio_unitario" >= 0);`,
    schemaTables: [
      {
        name: 'ventas_detalleboleta (PROTEGIDA)',
        description: 'La base de datos rechaza inserciones corruptas con cantidades 0 o negativas',
        columns: [
          { name: 'id', type: 'BIGINT', isPk: true },
          { name: 'boleta_id', type: 'BIGINT', isFk: true },
          { name: 'producto_id', type: 'BIGINT', isFk: true },
          { name: 'precio_unitario', type: 'NUMERIC(10,2) CHECK (>= 0)' },
          { name: 'cantidad', type: 'INTEGER CHECK (> 0)' },
          { name: 'total_linea', type: 'NUMERIC(10,2) (Calculado en save())' },
        ],
      },
    ],
    architectureInsight: 'Las validaciones en Python (como forms.is_valid()) protegen las vistas web, pero un script, una tarea de Celery o un query directo podrían insertar cantidad=0. Agregar CheckConstraint a nivel de base de datos es la mejor práctica de ingeniería para garantizar integridad absoluta pase lo que pase.',
  },
  {
    id: 5,
    migrationFile: '0005_sembrar_categorias_iniciales.py',
    badge: 'Paso 5: Migración de Datos',
    title: 'Sembrado Idempotente con RunPython',
    goal: 'Crear una migración que no cambie la estructura de tablas (DDL), sino que inserte datos maestros de catálogo (DML) de forma automática e idempotente.',
    terminalCommand: `(venv) C:\\proyectos\\django\\ventas> python manage.py makemigrations ventas --empty --name sembrar_categorias_iniciales
Migrations for 'ventas':
  ventas/migrations/0005_sembrar_categorias_iniciales.py

(venv) C:\\proyectos\\django\\ventas> python manage.py migrate
Applying ventas.0005_sembrar_categorias_iniciales... OK`,
    modelsCode: `# ventas/migrations/0005_sembrar_categorias_iniciales.py
from django.db import migrations

CATEGORIAS_INICIALES = [
    {"nombre": "Bebidas y Cafetería", "descripcion": "Cafés de grano, té e infusiones"},
    {"nombre": "Pastelería", "descripcion": "Tortas, muffins y galletas artesanales"},
    {"nombre": "Snacks y Bocadillos", "descripcion": "Empanadas y sándwiches frescos"},
]

def sembrar_datos(apps, schema_editor):
    # REGLA CRÍTICA: No importar "from ventas.models import Categoria"
    # Usar siempre apps.get_model() para usar la versión histórica del modelo
    Categoria = apps.get_model('ventas', 'Categoria')
    for cat in CATEGORIAS_INICIALES:
        Categoria.objects.get_or_create(
            nombre=cat["nombre"],
            defaults={"descripcion": cat["descripcion"]}
        )

def desempadronar_datos(apps, schema_editor):
    Categoria = apps.get_model('ventas', 'Categoria')
    nombres = [c["nombre"] for c in CATEGORIAS_INICIALES]
    Categoria.objects.filter(nombre__in=nombres).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('ventas', '0004_constraints_reglas_negocio'),
    ]

    operations = [
        migrations.RunPython(sembrar_datos, reverse_code=desempadronar_datos),
    ]`,
    sqlSnippet: `-- Ejecutado internamente en Python via ORM:
INSERT INTO "ventas_categoria" ("nombre", "descripcion") 
VALUES 
  ('Bebidas y Cafetería', 'Cafés de grano, té e infusiones'),
  ('Pastelería', 'Tortas, muffins y galletas artesanales'),
  ('Snacks y Bocadillos', 'Empanadas y sándwiches frescos')
ON CONFLICT ("nombre") DO NOTHING;`,
    schemaTables: [
      {
        name: 'ventas_categoria (CON DATOS DE CATÁLOGO)',
        description: 'Las categorías esenciales quedan disponibles en cualquier entorno nuevo con solo correr migrate',
        columns: [
          { name: '1', type: 'Bebidas y Cafetería' },
          { name: '2', type: 'Pastelería' },
          { name: '3', type: 'Snacks y Bocadillos' },
        ],
      },
    ],
    architectureInsight: 'Las migraciones de datos con RunPython resuelven el problema de despliegue en producción: cualquier nuevo desarrollador o servidor de CI/CD que clone el repositorio y ejecute "python manage.py migrate" tendrá automáticamente las tablas creadas y las categorías iniciales listas para vender.',
  },
];

export default function DjangoMigrationStepper() {
  const [activeStepId, setActiveStepId] = useState<number>(1);
  const currentStep = MIGRATION_STEPS.find((s) => s.id === activeStepId) || MIGRATION_STEPS[0];

  return (
    <div className="not-prose my-8 rounded-2xl border border-emerald-200/80 bg-white text-slate-800 shadow-xl overflow-hidden font-sans">
      {/* Header */}
      <div className="bg-gradient-to-r from-emerald-50 via-teal-50/70 to-slate-50 p-5 border-b border-emerald-100 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100/80 text-emerald-800 text-xs font-mono font-bold tracking-wider border border-emerald-200 mb-2 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-emerald-600 animate-pulse" />
            LÍNEA DE TIEMPO EVOLUTIVA
          </div>
          <h3 className="text-xl font-black text-slate-900 m-0 tracking-tight">
            Evolución de la Base de Datos: Sistema de Boletas POS
          </h3>
          <p className="text-xs text-slate-600 mt-1 m-0">
            Avanza paso a paso viendo cómo nacen las tablas, se añaden relaciones y se aplican migraciones seguras sin pérdida de datos.
          </p>
        </div>

        {/* Current Migration File Badge */}
        <div className="bg-white px-3.5 py-2 rounded-xl border border-slate-200 shadow-sm flex items-center gap-2 self-start md:self-auto">
          <span className="text-xs text-slate-500 font-medium">Archivo Migración:</span>
          <span className="text-xs font-mono text-emerald-800 font-bold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
            {currentStep.migrationFile}
          </span>
        </div>
      </div>

      {/* Stepper Navigation Buttons */}
      <div className="bg-slate-50/90 p-3 border-b border-slate-200 flex items-center gap-2.5 overflow-x-auto">
        {MIGRATION_STEPS.map((step) => {
          const isActive = step.id === activeStepId;
          const isCompleted = step.id < activeStepId;

          return (
            <button
              key={step.id}
              type="button"
              onClick={() => setActiveStepId(step.id)}
              className={`flex-1 min-w-[175px] text-left px-3.5 py-2.5 rounded-xl transition-all border flex items-center gap-2.5 ${
                isActive
                  ? 'bg-white border-emerald-500 text-slate-900 shadow-md ring-2 ring-emerald-500/20'
                  : 'bg-white/80 border-slate-200/90 text-slate-600 hover:text-slate-900 hover:bg-white hover:border-slate-300 shadow-sm'
              }`}
            >
              <div
                className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold font-mono transition-colors shrink-0 ${
                  isActive
                    ? 'bg-emerald-600 text-white shadow-sm'
                    : isCompleted
                    ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                    : 'bg-slate-100 text-slate-500 border border-slate-200'
                }`}
              >
                {step.id}
              </div>
              <div className="truncate">
                <div className={`text-[11px] font-bold truncate ${isActive ? 'text-emerald-800' : 'text-slate-800'}`}>
                  {step.badge}
                </div>
                <div className="text-[10px] text-slate-500 truncate">{step.title}</div>
              </div>
            </button>
          );
        })}
      </div>

      {/* Content Area */}
      <div className="p-6 space-y-6 bg-slate-50/40">
        {/* Goal Description */}
        <div className="bg-white p-4 rounded-xl border border-emerald-200/80 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-700 block mb-1">
              🎯 Objetivo del Paso {currentStep.id}:
            </span>
            <h4 className="text-base font-bold text-slate-900 m-0">{currentStep.title}</h4>
            <p className="text-xs text-slate-600 mt-1 m-0 leading-relaxed">{currentStep.goal}</p>
          </div>
          <div className="flex gap-2 shrink-0">
            <button
              type="button"
              disabled={activeStepId === 1}
              onClick={() => setActiveStepId((p) => Math.max(1, p - 1))}
              className="px-3.5 py-1.5 rounded-lg bg-white hover:bg-slate-50 border border-slate-300 disabled:opacity-40 disabled:cursor-not-allowed text-xs font-bold text-slate-700 shadow-sm transition-all"
            >
              ← Anterior
            </button>
            <button
              type="button"
              disabled={activeStepId === MIGRATION_STEPS.length}
              onClick={() => setActiveStepId((p) => Math.min(MIGRATION_STEPS.length, p + 1))}
              className="px-3.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 disabled:opacity-40 disabled:cursor-not-allowed text-xs font-bold text-white shadow-sm transition-all"
            >
              Siguiente Paso →
            </button>
          </div>
        </div>

        {/* Two-Column Grid: Code vs Architecture & Schema */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Column (7 cols): Python Code & Terminal */}
          <div className="lg:col-span-7 space-y-4">
            {/* Terminal Command Box */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs font-mono font-bold text-slate-700 flex items-center gap-1.5">
                  <span className="text-cyan-600">💻</span> Terminal: Generar y Aplicar Migración
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded bg-cyan-100 text-cyan-800 font-mono font-bold border border-cyan-200">
                  Bash / CMD
                </span>
              </div>
              <div className="bg-slate-900 p-3 rounded-xl border border-slate-800 font-mono text-xs text-slate-200 leading-relaxed overflow-x-auto shadow-md">
                <pre className="m-0 font-mono">{currentStep.terminalCommand}</pre>
              </div>
            </div>

            {/* Python models.py Code */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs font-mono font-bold text-slate-700 flex items-center gap-1.5">
                  <span className="text-blue-600">🐍</span> Código en Python (<code>ventas/models.py</code>)
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded bg-blue-100 text-blue-800 font-mono font-bold border border-blue-200">
                  Django Models
                </span>
              </div>
              <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 font-mono text-xs text-emerald-300 leading-relaxed overflow-x-auto max-h-[380px] shadow-md">
                <pre className="m-0 font-mono">{currentStep.modelsCode}</pre>
              </div>
            </div>

            {/* SQL Migration Output */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs font-mono font-bold text-slate-700 flex items-center gap-1.5">
                  <span className="text-amber-600">⚡</span> SQL Real Ejecutado (<code>sqlmigrate ventas {currentStep.migrationFile.slice(0, 4)}</code>)
                </span>
              </div>
              <div className="bg-slate-900 p-3 rounded-xl border border-slate-800 font-mono text-[11px] text-amber-300 leading-relaxed overflow-x-auto max-h-[180px] shadow-md">
                <pre className="m-0 font-mono">{currentStep.sqlSnippet}</pre>
              </div>
            </div>
          </div>

          {/* Right Column (5 cols): Schema Inspector & Architectural Insight */}
          <div className="lg:col-span-5 space-y-4 flex flex-col justify-between">
            {/* Schema Visualizer */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold text-slate-800 flex items-center gap-1.5">
                  <span>🗄️</span> Esquema en Base de Datos (Tablas Resultantes):
                </span>
                <span className="text-[10px] text-slate-500 font-mono font-semibold bg-white px-2 py-0.5 rounded border border-slate-200 shadow-sm">
                  {currentStep.schemaTables.length} tablas activas
                </span>
              </div>

              <div className="space-y-3">
                {currentStep.schemaTables.map((tbl, i) => (
                  <div key={i} className="p-3.5 rounded-xl bg-white border border-slate-200 shadow-sm">
                    <div className="flex items-center justify-between border-b border-slate-100 pb-2 mb-2">
                      <span className="text-xs font-mono font-bold text-emerald-800 flex items-center gap-1.5">
                        <span>📋</span> {tbl.name}
                      </span>
                      <span className="text-[10px] text-slate-500 font-bold bg-slate-100 px-1.5 py-0.5 rounded border border-slate-200">
                        {tbl.columns.length} cols
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-500 mb-2.5">{tbl.description}</p>
                    <div className="space-y-1">
                      {tbl.columns.map((col, cIdx) => (
                        <div
                          key={cIdx}
                          className="flex items-center justify-between text-[11px] font-mono px-2.5 py-1 rounded bg-slate-50/80 border border-slate-200/70"
                        >
                          <span className="flex items-center gap-1 text-slate-800 font-medium">
                            {col.isPk && (
                              <span className="text-[9px] bg-amber-100 text-amber-800 px-1 py-0.2 rounded border border-amber-300 font-bold">
                                🔑 PK
                              </span>
                            )}
                            {col.isFk && (
                              <span className="text-[9px] bg-sky-100 text-sky-800 px-1 py-0.2 rounded border border-sky-300 font-bold">
                                🔗 FK
                              </span>
                            )}
                            {col.name}
                          </span>
                          <span className="text-[10px] text-slate-500">{col.type}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Architecture Tip / Warning Box */}
            <div className="p-4 rounded-xl bg-emerald-50/90 border border-emerald-300 text-emerald-950 text-xs space-y-1.5 shadow-sm">
              <div className="flex items-center gap-2 font-bold text-emerald-900">
                <span className="text-base">💡</span>
                <span>Clave de Arquitectura en Producción:</span>
              </div>
              <p className="text-[11px] leading-relaxed text-slate-700 m-0">
                {currentStep.architectureInsight}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
