import type { Slide } from '../../../types/slides';

export const modeloBdSlides: Slide[] = [
  {
    id: 1,
    type: 'cover',
    title: '5. Modelos y Tipos de Datos: De Python a SQL 🧱',
    subtitle: 'Mapeo Objeto-Relacional (ORM), tipos de campos, migraciones y arquitectura relacional',
    badge: 'Django · Lección 5',
    content: 'Aprende cómo Django traduce clases y atributos de Python en tablas y columnas físicas de base de datos relacional (PostgreSQL, SQLite, MySQL) de forma transparente y eficiente.',
    bulletPoints: [
      '🧱 Modelos como clases de Python que heredan de models.Model',
      '🔄 El puente de migraciones: makemigrations, sqlmigrate y migrate',
      '📊 Catálogo exhaustivo de campos: CharField, DecimalField, DateTime y UUID',
      '🔗 Arquitectura de relaciones relacionales: 1 a N (ForeignKey), 1 a 1 y N a M'
    ],
    keyTakeaway: 'El ORM de Django te permite diseñar esquemas de datos relacionales robustos y seguros sin escribir sentencias SQL manuales.'
  },
  {
    id: 2,
    type: 'concept',
    title: '1. ¿Qué es un Modelo y cómo se conecta a SQL?',
    badge: 'Concepto ORM',
    content: 'Un ORM (Object-Relational Mapper) es una capa de abstracción que traduce clases y atributos de Python en tablas, columnas y tipos de datos relacionales.',
    visualChart: {
      headers: ['Concepto en Python (Django)', 'Equivalente en Base de Datos (SQL)', 'Ejemplo SQL / Físico'],
      rows: [
        ['`class Articulo(models.Model)`', 'Tabla física relacional', '`CREATE TABLE "blog_articulo" (...)`'],
        ['`titulo = models.CharField(...)`', 'Columna tipada con restricciones', '`"titulo" varchar(150) NOT NULL`'],
        ['`art = Articulo(titulo="Django")`', 'Fila o registro individual (`Row`)', '`INSERT INTO "blog_articulo" VALUES (...)`'],
        ['`id` (generado automáticamente)', 'Clave Primaria (`Primary Key`)', '`"id" bigint NOT NULL PRIMARY KEY`']
      ]
    },
    keyTakeaway: 'Cada modelo es una tabla; cada atributo es una columna; cada instancia en memoria es una fila física en el motor de base de datos.'
  },
  {
    id: 3,
    type: 'code',
    title: '2. El Puente de las Migraciones: Flujo en 3 Pasos',
    badge: 'Flujo de Trabajo',
    content: 'Cuando defines un modelo en models.py, la base de datos aún no sabe nada. El flujo para materializar tus cambios consta de 3 comandos esenciales:',
    bulletPoints: [
      '1. makemigrations: Compara tus modelos actuales con el historial y genera el archivo en Python (ej: 0001_initial.py)',
      '2. sqlmigrate <app> <num>: El comando más educativo: muestra el código SQL puro y exacto que Django enviará al motor',
      '3. migrate: Ejecuta físicamente las sentencias SQL en el motor de base de datos'
    ],
    codeSnippet: {
      filename: 'terminal.sh',
      lang: 'bash',
      code: `# 1. Detectar cambios en models.py y generar migración
$ python manage.py makemigrations blog
Migrations for 'blog':
  blog/migrations/0001_initial.py
    - Create model Articulo

# 2. Auditar el SQL puro antes de tocar la base de datos
$ python manage.py sqlmigrate blog 0001
CREATE TABLE "blog_articulo" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "titulo" varchar(150) NOT NULL
);

# 3. Aplicar las sentencias físicas en PostgreSQL / SQLite
$ python manage.py migrate
Applying blog.0001_initial... OK`,
      explanation: 'sqlmigrate te permite revisar los CREATE TABLE y tipos de columnas generados antes de aplicarlos en producción.'
    },
    keyTakeaway: 'sqlmigrate es la mejor herramienta para auditar qué hace Django tras bambalinas en tu motor SQL.'
  },
  {
    id: 4,
    type: 'concept',
    title: '3. models.CharField y el Parámetro Obligatorio max_length',
    badge: 'Campos de Texto',
    content: 'models.CharField representa cadenas de texto de longitud limitada. A diferencia de otros campos, Django EXIGE obligatoriamente definir max_length.',
    bulletPoints: [
      'Si omites max_length, Django arrojará un error de SystemCheck antes de arrancar',
      'En PostgreSQL y MySQL genera un tipo físico VARCHAR(n) que optimiza memoria e índices',
      'En SQLite genera VARCHAR(n), manteniendo compatibilidad con motores de alta escala',
      'Usa CharField para textos cortos con longitud previsible: nombres, títulos, slugs, códigos'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `from django.db import models

class Producto(models.Model):
    # max_length es OBLIGATORIO en CharField
    codigo = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=100)
    
    # Para textos largos sin longitud fija usa TextField (no exige max_length)
    descripcion = models.TextField(blank=True)`,
      explanation: 'CharField optimiza índices y reservas de buffer; TextField se almacena fuera de la fila principal en motores relacionales.'
    },
    keyTakeaway: 'Usa CharField con un max_length razonable para datos cortos e indexables; usa TextField para párrafos y notas extensas.'
  },
  {
    id: 5,
    type: 'diagram',
    title: '4. El Gran Dilema: null=True vs blank=True',
    badge: 'Restricciones',
    content: 'Uno de los conceptos que más confunde a los desarrolladores en Django. ¿Afectan a la Base de Datos o al Formulario?',
    visualChart: {
      headers: ['Propiedad / Flag', 'Ámbito de Acción', 'Efecto Técnico', 'Cuándo Usar'],
      rows: [
        ['`null=False` (por defecto)', 'Base de Datos (SQL)', 'Columna `NOT NULL`; rechaza inserciones vacías en BD', 'Casi siempre por defecto'],
        ['`null=True`', 'Base de Datos (SQL)', 'Columna `NULL`; permite almacenar el valor nulo SQL', 'Fechas, números o claves foráneas opcionales'],
        ['`blank=False` (por defecto)', 'Formularios / Admin (Python)', 'Obligatorio en HTML y formularios de Django', 'Campos requeridos por interfaz'],
        ['`blank=True`', 'Formularios / Admin (Python)', 'Permite enviar el campo vacío desde la UI', 'Campos opcionales para el usuario']
      ]
    },
    keyTakeaway: '⚠️ Regla de Oro: NUNCA uses null=True en CharField o TextField. Si el texto es opcional, usa solo blank=True para guardar una cadena vacía "" uniforme.'
  },
  {
    id: 6,
    type: 'code',
    title: '5. DecimalField vs FloatField: ¿Por qué NUNCA Float para Dinero?',
    badge: 'Precisión Numérica',
    content: 'Uno de los errores más peligrosos en desarrollo backend: usar FloatField para precios, saldos o facturación.',
    bulletPoints: [
      'Los números float usan IEEE 754 de base 2: producen micro-errores como 0.1 + 0.2 = 0.30000000000000004',
      'En sistemas contables o pasarelas de pago, los micro-errores causan descuadres de caja inaceptables',
      'DecimalField utiliza tipo NUMERIC en SQL y la clase Decimal de Python para precisión fija exacta',
      'Exige dos parámetros obligatorios: max_digits (total de dígitos) y decimal_places (decimales)'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `class Factura(models.Model):
    # ❌ PELIGRO: FloatField causa errores de redondeo
    # total_inseguro = models.FloatField()

    # ✅ CORRECTO: DecimalField garantiza precisión bancaria
    # max_digits=10, decimal_places=2 -> hasta 99,999,999.99
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    iva = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)`,
      explanation: 'DecimalField genera columnas SQL "numeric(10, 2)" sin pérdida de centavos en cálculos contables.'
    },
    keyTakeaway: 'Usa FloatField solo para métricas científicas aproximadas; para dinero, saldos y precios SIEMPRE usa DecimalField.'
  },
  {
    id: 7,
    type: 'concept',
    title: '6. Fechas, Booleanos y UUIDs en Django',
    badge: 'Campos Especiales',
    content: 'Django incluye tipos especializados para resolver necesidades reales de negocio de forma nativa.',
    bulletPoints: [
      'BooleanField: Columnas booleanas (True/False en Python; bool/boolean en SQL)',
      'DateField vs DateTimeField: Con o sin hora y soporte de zona horaria',
      'auto_now_add=True: Graba la fecha/hora solo UNA vez al momento de crear la fila (created_at)',
      'auto_now=True: Actualiza la fecha/hora automáticamete en CADA save() (updated_at)',
      'UUIDField: Genera claves primarias con uuid.uuid4() no secuenciales para proteger la privacidad'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `import uuid
from django.db import models

class Articulo(models.Model):
    # ID universal imposible de adivinar mediante enumeración
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    activo = models.BooleanField(default=True)
    
    # Timestamps estándar de auditoría
    created_at = models.DateTimeField(auto_now_add=True)  # Solo en INSERT
    updated_at = models.DateTimeField(auto_now=True)      # En cada UPDATE`,
      explanation: 'auto_now_add y auto_now automatizan la auditoría temporal de registros sin intervención manual.'
    },
    keyTakeaway: 'Los campos de auditoría created_at y updated_at son una práctica estándar en cualquier modelo profesional.'
  },
  {
    id: 8,
    type: 'diagram',
    title: '7. Panorama de Relaciones: 1 a N, 1 a 1 y N a M',
    badge: 'Relaciones Relacionales',
    content: 'Las bases de datos relacionales obtienen su poder al vincular entidades entre sí. Django modela estas relaciones con 3 campos clave:',
    visualChart: {
      headers: ['Tipo de Relación', 'Campo Django', 'Físicamente en la BD SQL', 'Navegación en Python'],
      rows: [
        ['**1 a N** (Uno a Muchos)', '`models.ForeignKey(B, on_delete=...)`', 'Columna física `b_id` en tabla A + Índice `B-Tree`', '`a.b` (objeto) | `b.as.all()` (`QuerySet`)'],
        ['**1 a 1** (Uno a Uno)', '`models.OneToOneField(B, on_delete=...)`', 'Columna física `b_id` en tabla A + Restricción `UNIQUE`', '`a.b` (objeto) | `b.a` (objeto directo)'],
        ['**N a M** (Muchos a Muchos)', '`models.ManyToManyField(B)`', 'Tabla intermedia con claves foráneas cruzadas', '`a.bs.all()` | `b.as.all()` (`.add`, `.remove`)']
      ]
    },
    keyTakeaway: 'En 1:N y 1:1 la clave foránea vive en una de las tablas; en N:M se requiere obligatoriamente una tabla intermedia.'
  },
  {
    id: 9,
    type: 'code',
    title: '8. Relación 1 a N (ForeignKey) y Políticas on_delete',
    badge: 'ForeignKey',
    content: 'La relación más común: Una Categoría tiene muchos Productos; cada Producto pertenece a una sola Categoría.',
    bulletPoints: [
      'Django agrega automáticamente el sufijo _id a la columna física (ej: categoria_id)',
      'Crea un índice B-Tree automático para que las consultas por clave foránea sean ultra veloces',
      'El parámetro on_delete es OBLIGATORIO: define qué ocurre al eliminar el registro padre',
      'CASCADE: borra los hijos en cascada | PROTECT: bloquea el borrado con ProtectedError'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,     # Borra productos si se borra la categoría
        # on_delete=models.PROTECT,   # ✅ Recomendado para evitar pérdidas accidentales
        related_name='productos'      # Acceso inverso: categoria.productos.all()
    )`,
      explanation: 'related_name define cómo se accede desde el modelo padre hacia sus hijos.'
    },
    keyTakeaway: 'Para entidades críticas como ventas o clientes, usa models.PROTECT para evitar borrados accidentales de información histórica.'
  },
  {
    id: 10,
    type: 'code',
    title: '9. Relación 1 a 1: OneToOneField',
    badge: 'OneToOneField',
    content: 'Un registro de la Tabla A se corresponde con exactamente uno de la Tabla B. Muy común para extender el modelo User oficial.',
    bulletPoints: [
      'A nivel SQL es idéntico a una ForeignKey, pero Django le añade la restricción UNIQUE en la columna foránea',
      'A nivel Python, el acceso inverso retorna directamente la instancia única (no un QuerySet)',
      'Si el perfil no existe, el acceso inverso lanza la excepción DoesNotExist'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `from django.contrib.auth.models import User
from django.db import models

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    biografia = models.TextField(blank=True)
    telefono = models.CharField(max_length=20, blank=True)

# Acceso en Python:
usuario = User.objects.get(username="ada_lovelace")
print(usuario.perfil.biografia)  # ✅ Directo al objeto, ¡sin .all()!`,
      explanation: 'OneToOneField asegura que un usuario no pueda tener más de un perfil en el sistema.'
    },
    keyTakeaway: 'Usa OneToOneField para extender modelos del núcleo sin modificar el código fuente original de librerías externas.'
  },
  {
    id: 11,
    type: 'code',
    title: '10. Relación Muchos a Muchos: models.ManyToManyField',
    badge: 'ManyToManyField',
    content: 'Un Artículo puede tener varias Etiquetas, y cada Etiqueta clasifica a múltiples Artículos. Django crea automáticamente la tabla intermedia por ti.',
    bulletPoints: [
      'models.ManyToManyField(Modelo) define la relación simétrica bidireccional',
      'Crea silenciosamente la tabla puente: "blog_articulo_etiquetas" con articulo_id y etiqueta_id',
      'related_name="articulos" permite consultar desde el otro extremo: etiqueta.articulos.all()',
      'Métodos ORM clave: .add() para asociar, .remove() para desvincular, y .clear() para vaciar'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `from django.db import models

class Etiqueta(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

class Articulo(models.Model):
    titulo = models.CharField(max_length=150)
    # Muchos a Muchos: crea la tabla física "blog_articulo_etiquetas"
    etiquetas = models.ManyToManyField(
        Etiqueta,
        related_name='articulos',
        blank=True
    )

# Operaciones en consultas ORM:
art = Articulo.objects.get(id=1)
tag = Etiqueta.objects.get(nombre="Django")

art.etiquetas.add(tag)       # Inserta fila en tabla intermedia
art.etiquetas.all()          # QuerySet de etiquetas del artículo
etiqueta.articulos.all()     # QuerySet inverso usando related_name
art.etiquetas.remove(tag)    # Elimina fila de la tabla intermedia`,
      explanation: 'ManyToManyField gestiona automáticamente las claves foráneas cruzadas y la integridad de la tabla intermedia.'
    },
    keyTakeaway: 'Usa ManyToManyField estándar cuando la unión de dos entidades no requiera almacenar columnas o metadatos adicionales.'
  },
  {
    id: 12,
    type: 'code',
    title: '11. Tabla Intermedia Personalizada con through',
    badge: 'through argument',
    content: '¿Qué pasa cuando la relación en sí misma necesita datos? Por ejemplo, una Inscripción con fecha, rol o nota del estudiante en un Curso.',
    bulletPoints: [
      'through="ModeloIntermedio" indica a Django que use una tabla propia en lugar de la automática',
      'El modelo intermedio debe contener al menos 2 ForeignKeys: una a cada modelo extremo',
      'Permite agregar cualquier campo adicional: DateTimeField, DecimalField, BooleanField, etc.',
      'Excelente para membresías, suscripciones con fechas de vigencia o inventarios con cantidad'
    ],
    codeSnippet: {
      filename: 'models.py',
      lang: 'python',
      code: `from django.db import models

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100)

class Curso(models.Model):
    titulo = models.CharField(max_length=150)
    # Relación M:M con tabla intermedia explícita:
    estudiantes = models.ManyToManyField(
        Estudiante,
        through='Inscripcion',
        related_name='cursos'
    )

# Modelo Intermedio con metadatos del negocio:
class Inscripcion(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    fecha_inscripcion = models.DateTimeField(auto_now_add=True)
    calificacion_final = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    activo = models.BooleanField(default=True)`,
      explanation: 'El argumento through te da control absoluto sobre los atributos y reglas de la tabla intermedia.'
    },
    keyTakeaway: 'Usa el argumento through siempre que la relación de muchos a muchos tenga atributos propios como fechas, notas o estados.'
  },
  {
    id: 13,
    type: 'summary',
    title: 'Resumen y Mejores Prácticas de Modelos Django 🏆',
    badge: 'Guía Definitiva',
    content: 'Domina las bases del diseño de datos en Django para construir aplicaciones robustas, escalables y mantenibles:',
    bulletPoints: [
      '1. Inspecciona siempre con sqlmigrate antes de ejecutar migraciones complejas en producción',
      '2. Evita null=True en CharField y TextField; usa blank=True para campos opcionales',
      '3. Usa DecimalField para cualquier dato monetario o financiero; nunca FloatField',
      '4. Añade timestamps de auditoría (created_at y updated_at) en todos tus modelos de negocio',
      '5. Asigna nombres descriptivos a related_name en tus ForeignKey y ManyToManyField',
      '6. Protege la integridad referencial con on_delete=models.PROTECT en datos críticos'
    ],
    keyTakeaway: 'Un buen diseño de modelos en Django se traduce en un esquema SQL limpio, índices optimizados y consultas ORM eficientes.'
  }
];
